spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aitest01}
    username: ${SPRING_DATASOURCE_USERNAME:ai01}
    password: ${SPRING_DATASOURCE_PASSWORD:ai01}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
