# =========================================================
# Receivers
# =========================================================

receivers:

  otlp:

    protocols:

      # OTLP gRPC
      grpc:
        endpoint: 0.0.0.0:4317

      # OTLP HTTP
      # ai-agent از این ورودی استفاده می‌کند.
      http:
        endpoint: 0.0.0.0:4318


# =========================================================
# Processors
# =========================================================

processors:

  # Spanها قبل از ارسال به Phoenix
  # به صورت Batch ارسال می‌شوند.
  batch:


# =========================================================
# Exporters
# =========================================================

exporters:

  # Phoenix داخل همان Docker Network قرار دارد.
  otlp/phoenix:

    endpoint: phoenix:4317

    tls:
      insecure: true


# =========================================================
# Pipelines
# =========================================================

service:

  pipelines:

    traces:

      receivers:
        - otlp

      processors:
        - batch

      exporters:
        - otlp/phoenix