package com.example.ai01.service.deterministic;
import com.example.ai01.agent.model.*;
import com.example.ai01.agent.model.ruleextraction.ArchitectureRule;
import org.springframework.stereotype.Component;
import java.util.*;
import java.util.stream.Collectors;
@Component public class ApiRuleRepository extends AbstractRuleRepository {
 public ApiRuleRepository(SourceTextProvider p){super(p);} public String strategyKey(){return "API";} public boolean supports(String c){return RuleCode.belongsTo(c,"API");}
 public List<ViolationFinding> evaluate(ArchitectureRule r,PackageNode p){return switch(RuleCode.normalize(r.id())){case"02013API002"->authId(r,p);case"02016API005"->paginationNames(r,p);case"02017API006"->sortingNames(r,p);case"03010API001"->requestBody(r,p);case"03028API001"->paginationMetadata(r,p);case"03038API002"->errorDetails(r,p);case"03039API003"->detailPath(r,p);case"06031API001"->queryConflict(r,p,"fields");case"06032API002"->queryConflict(r,p,"expand");default->evaluateSourceContract(r,p);};}
 private List<ViolationFinding> authId(ArchitectureRule r,PackageNode p){List<ViolationFinding>o=new ArrayList<>();for(JavaFile f:controllers(p))for(Method m:f.methods()){String path=endpointPath(f,m);if(path!=null&&usesAuth(m)&&!Arrays.asList(path.split("/")).contains("self"))o.add(finding(r,f.path(),"Authorization-derived endpoint "+m.name()+" does not use /self: "+path,"Use self as the pseudo-id path segment."));}return List.copyOf(o);}
 private List<ViolationFinding> sortingNames(ArchitectureRule r,PackageNode p){List<ViolationFinding>o=new ArrayList<>();Set<String>a=Set.of("sort","sortby","sort_by","order","direction","sortdirection");for(JavaFile f:controllers(p))for(Method m:f.methods()){if(!endpoint(m))continue;Set<String>n=names(m);if(n.stream().noneMatch(a::contains))continue;if(!(n.contains("sortby")&&n.contains("order")))o.add(finding(r,f.path(),"Endpoint "+m.name()+" uses non-standard sorting parameters: "+n,"Use sortBy and order together."));}return List.copyOf(o);}
 private List<ViolationFinding> requestBody(ArchitectureRule r,PackageNode p){List<ViolationFinding>o=new ArrayList<>();Map<String,JavaFile>idx=index(p);for(JavaFile c:controllers(p))for(Method m:c.methods())for(Parameter q:m.parameters()){if(!ann(q.annotations(),"RequestBody"))continue;JavaFile d=idx.get(simple(q.type()));if(d==null)continue;Field meta=field(d,"metadata");boolean required=meta!=null&&(ann(meta.annotations(),"NotNull")||ann(meta.annotations(),"NotBlank"));boolean wrapped=d.fields().stream().map(Field::name).map(String::toLowerCase).anyMatch(Set.of("data","body","payload","request")::contains);if(required||wrapped)o.add(finding(r,d.path(),"Request DTO has required metadata or a business-content wrapper.","Keep metadata optional and business fields directly in the body."));}return List.copyOf(o);}
 private List<ViolationFinding> paginationMetadata(ArchitectureRule r,PackageNode p){List<ViolationFinding>o=new ArrayList<>();Map<String,JavaFile>idx=index(p);for(JavaFile c:controllers(p))for(Method m:c.methods()){if(!endpoint(m)||!paginated(m))continue;JavaFile d=idx.get(simple(m.returnType()));if(d==null)continue;Field meta=field(d,"metadata");JavaFile mt=meta==null?null:idx.get(simple(meta.type()));if(meta==null||mt==null||field(mt,"pagination")==null)o.add(finding(r,d.path(),"Paginated response does not expose metadata.pagination.","Place pagination inside metadata."));}return List.copyOf(o);}
 private List<ViolationFinding> errorDetails(ArchitectureRule r,PackageNode p){List<ViolationFinding>o=new ArrayList<>();for(JavaFile f:files(p)){if(!errorDto(f))continue;Field d=field(f,"details");if(d==null)continue;String t=safe(d.type());boolean object=!t.equals("String")&&!t.equals("Object")&&!t.matches("Map(?:<.*>)?");if(!object||!schema(d))o.add(finding(r,f.path(),"Error details is not a documented typed object.","Use a typed details object with @Schema(description=...)."));}return List.copyOf(o);}
 private List<ViolationFinding> detailPath(ArchitectureRule r,PackageNode p){boolean hash=sourceTextProvider.readAll(p).values().stream().anyMatch(s->s.contains("\"#\"")||s.contains("'#'"));if(hash)return List.of();return files(p).stream().filter(this::errorDto).filter(f->field(f,"details")!=null||field(f,"path")!=null).filter(f->sourceTextProvider.read(f).contains("path")).map(f->finding(r,f.path(),"Error detail path is used but # formatting was not found.","Append # and field name to the resource URL.")).toList();}
 private List<ViolationFinding> queryConflict(ArchitectureRule r,PackageNode p,String reserved){List<ViolationFinding>o=new ArrayList<>();for(JavaFile f:controllers(p))for(Method m:f.methods())if(endpoint(m)&&names(m).contains(reserved))o.add(finding(r,f.path(),"Endpoint "+m.name()+" declares reserved query parameter '"+reserved+"'.","Remove the conflicting query parameter or rename it according to the API standard."));return List.copyOf(o);}
 private List<ViolationFinding> paginationNames(ArchitectureRule r,PackageNode p){List<ViolationFinding>o=new ArrayList<>();for(JavaFile f:controllers(p))for(Method m:f.methods()){if(!endpoint(m)||!paginated(m)||hasPageable(m))continue;Set<String>n=names(m);boolean a=n.contains("page")&&n.contains("size")&&!n.contains("cursor"),b=n.contains("cursor")&&n.contains("size")&&!n.contains("page");if(!a&&!b)o.add(finding(r,f.path(),"Endpoint "+m.name()+" has invalid pagination parameters: "+n,"Use page+size or cursor+size."));}return List.copyOf(o);}
 private List<JavaFile>controllers(PackageNode p){return files(p).stream().filter(f->inLayer(f,"controller")||hasAnnotation(f,"Controller")||hasAnnotation(f,"RestController")).toList();}
 private boolean endpoint(Method m){return m.annotations().stream().map(Annotation::name).anyMatch(n->n.endsWith("Mapping"));} private boolean usesAuth(Method m){return m.parameters().stream().map(Parameter::type).map(this::simple).anyMatch(Set.of("Authentication","Principal","Jwt","SecurityContext")::contains);}
 private boolean paginated(Method m){Set<String>n=names(m);return hasPageable(m)||n.contains("page")||n.contains("cursor")||n.contains("size")||safe(m.returnType()).matches(".*(?:Page|Slice)<.*");} private boolean hasPageable(Method m){return m.parameters().stream().map(Parameter::type).map(this::simple).anyMatch("Pageable"::equals);} private Set<String>names(Method m){return m.parameters().stream().map(this::external).map(s->s.toLowerCase(Locale.ROOT)).collect(Collectors.toSet());}
 private String external(Parameter p){for(Annotation a:p.annotations())if(a.name().endsWith("RequestParam")){Map<String,String>x=a.attributes()==null?Map.of():a.attributes();String v=x.getOrDefault("name",x.get("value"));if(v!=null&&!v.isBlank())return clean(v);}return safe(p.name());}
 private String endpointPath(JavaFile f,Method m){String b=mapping(m.annotations());if(b==null)return null;String a=mapping(f.annotations());return((a==null?"":a)+"/"+b).replaceAll("/+","/");} private String mapping(List<Annotation>as){for(Annotation a:as)if(a.name().endsWith("Mapping")){Map<String,String>x=a.attributes()==null?Map.of():a.attributes();return clean(x.getOrDefault("path",x.getOrDefault("value","")));}return null;}
 private Map<String,JavaFile>index(PackageNode p){return files(p).stream().collect(Collectors.toMap(this::typeName,f->f,(a,b)->a));} private String typeName(JavaFile f){return f.fileName().replaceFirst("\\.java$","");} private String simple(String t){String v=safe(t).replaceAll(".*<([^,>]+).*$","$1").replace("[]","").trim();int i=v.lastIndexOf('.');return i<0?v:v.substring(i+1);}
 private Field field(JavaFile f,String n){return f.fields().stream().filter(x->x.name().equalsIgnoreCase(n)).findFirst().orElse(null);} private boolean errorDto(JavaFile f){String n=typeName(f).toLowerCase();return n.contains("error")||n.contains("exception")||(field(f,"code")!=null&&field(f,"description")!=null);}
 private boolean schema(Field f){for(Annotation a:f.annotations())if(a.name().endsWith("Schema")){String d=(a.attributes()==null?Map.<String,String>of():a.attributes()).get("description");return d!=null&&!clean(d).isBlank();}return false;} private boolean ann(List<Annotation>a,String n){return a.stream().map(Annotation::name).anyMatch(v->v.equals(n)||v.endsWith("."+n));} private String clean(String v){return v==null?"":v.replaceAll("[\\\"'{}]","").trim();}
}
